Random things
decentraland/old-documentation pull request #103
Opened 2018-10-08 17:28 UTC by nearnshaw

Some random minor things

@oscnet please add changes to the translation

2018-10-10 01:21 UTC, eordano requested changes
Two minor things!

2018-10-10 01:21 UTC, eordano commented on _posts/development-guide/2018-01-09-external-3d-models.md
> +   > TIp: If you're using Blender and are on the _Blender Render_ tab, it creates a basic material by default, which is supported by Decentraland.
`Tip`

2018-10-10 01:21 UTC, eordano commented on _posts/development-guide/2018-01-09-external-3d-models.md
> +#### Create an animation
`How to`?

2018-10-10 01:47 UTC, nearnshaw commented
@eordano : I just made some adjustments based on your feedback

2018-10-10 01:57 UTC, nearnshaw commented
Ahí hice un par de ajustes en base a tus comments,
Gracias!

On Tue, Oct 9, 2018 at 10:21 PM Esteban Ordano <notifications@github.com>
wrote:

> *@eordano* requested changes on this pull request.
>
> Two minor things!
> ------------------------------
>
> In _posts/development-guide/2018-01-09-external-3d-models.md
> <https://github.com/decentraland/documentation/pull/103#discussion_r223911834>
> :
>
> > +Suppose you've imported a 3D model that uses a material that's not supported by Decentraland. You can easily change this material while still keeping the same texture and its mapping.
> +
> +<img src="/images/media/materials-not-supported.png" alt="Model without valid material" width="250"/>
> +
> +To swap the material:
> +
> +1. Check the current material's settings to see what texture files are being used and how they are configured.
> +2. Delete the current material from the mesh.
> +
> +   ![](/images/media/materials_delete_material.png)
> +
> +3. Create a new material.
> +
> +    <img src="/images/media/materials_new_material.png" alt="New default basic material" width="400"/>
> +
> +   > TIp: If you're using Blender and are on the _Blender Render_ tab, it creates a basic material by default, which is supported by Decentraland.
>
> Tip
> ------------------------------
>
> In _posts/development-guide/2018-01-09-external-3d-models.md
> <https://github.com/decentraland/documentation/pull/103#discussion_r223911877>
> :
>
> > @@ -284,53 +313,53 @@ In a Decentraland scene, you can use `weight` to blend several animations or to
>
>  > Tip: Instead of creating your own animations, you can also download generic animations and apply them to your model. For example, for 3D characters with human-like characteristics, you can download free or paid animations from [Mixamo](https://www.mixamo.com/#/).
>
> -#### Creating an animation
> +#### Create an animation
>
> How to?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/decentraland/documentation/pull/103#pullrequestreview-163155672>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADWGw0a8YLoq1CM0fqKmpnOGTNz9ipdtks5ujUuXgaJpZM4XNXVp>
> .
>

2018-10-11 18:33 UTC, eordano approved these changes

2018-10-11 18:34 UTC, merged