fix links
decentraland/old-documentation pull request #307
Opened 2020-05-07 20:40 UTC by nearnshaw

2020-05-09 09:21 UTC, HPrivakos commented
there is a typo in "_posts/market/2018-01-01-marketplace.md"
`Note: Use [land.decentraland.org](https://land.decentralnad.org) to:`
The url is "decentral-NA-d" instead for decentraland

2020-05-11 11:58 UTC, nearnshaw commented
Thanks @HPrivakos , well spotted!  Fixed

2020-05-22 12:42 UTC, 2fd requested changes

2020-05-22 12:42 UTC, 2fd commented on _posts/market/2020-02-16-land-manager.md
> +Access the Land manager at [https://land.decentraland.org](land.decentralnad.org)
```suggestion
Access the Land manager at [https://land.decentraland.org](land.decentraland.org)
```

2020-05-22 13:00 UTC, 2fd approved these changes

2020-05-26 14:46 UTC, merged