6.6.5
decentraland/old-documentation pull request #423
Opened 2021-05-17 17:24 UTC by nearnshaw

2021-05-18 17:32 UTC, kuruk-mm requested changes

2021-05-18 17:32 UTC, kuruk-mm commented on _posts/development-guide/2018-02-13-3d-model-animations.md
> +The `AnimationState` object has a `playing` boolean parameter that indicates if the animation is currently playing. For non-looping animations, this value reverts to _false_ when the animation finish
This doesn't happen sadly and it's very difficult to make it work... Same happens with the `Audio`.

We can trigger `play()` without anything, and if it was a non-looping animation finished, it will start over.

2021-05-18 17:32 UTC, kuruk-mm commented on _posts/development-guide/2018-02-13-3d-model-animations.md
> +- `reset`:_(optional)_ If true, it always plays the animation plays from the start.
maybe you can add `default: false` to let the reader knows what is the default behavior

2021-05-18 17:32 UTC, kuruk-mm commented on _posts/development-guide/2021-04-03-event-listeners.md
> +onEnterSceneObservable.add(() => {
I think you need to use:
```ts
onEnterSceneObservable.add((userId) => {
```

I don't know exactly if it is mandatory or not.

2021-05-18 17:32 UTC, kuruk-mm commented on _posts/development-guide/2021-04-03-event-listeners.md
> +  shape.value = "Expression: " + expressionId
Maybe you want to log that instead of assigning to a shape.value :thinking:

```suggestion
  log("Expression: ", expressionId)
```

2021-05-18 17:32 UTC, kuruk-mm commented on _posts/development-guide/2021-04-03-event-listeners.md
> +Note: This event is triggered by any player making an emote in the proximities of the player.
This event is only local and near the scene, or when the scene is in the range of vision.

2021-05-26 20:18 UTC, nearnshaw commented on _posts/development-guide/2021-04-03-event-listeners.md
> +onEnterSceneObservable.add(() => {
feature temporarily hidden

2021-05-26 22:04 UTC, kuruk-mm approved these changes

2021-05-26 22:04 UTC, kuruk-mm commented on _posts/development-guide/2018-02-22-user-data.md
> +> Note: The `Camera.istance.position` data is updated at a throttled rate of 10 times per second. Due to this, positions may lag slightly in relation to the scene that runs at 30 FPS under ideal cond
```suggestion
> Note: The `Camera.instance.position` data is updated at a throttled rate of 10 times per second. Due to this, positions may lag slightly in relation to the scene that runs at 30 FPS under ideal conditions.
```

2021-05-26 22:04 UTC, kuruk-mm commented on _posts/development-guide/2021-04-03-event-listeners.md
> +When the player changes the camera mode between 1st and 3rd person in or near your sene, this creates an event you can listen to.
```suggestion
When the player changes the camera mode between 1st and 3rd person in or near your scene, this creates an event you can listen to.
```

2021-05-26 22:12 UTC, merged