Wearables Docs Updates
decentraland/old-documentation pull request #443
Opened 2021-06-24 20:05 UTC by schallock

* Adds note that publication fee is non-refundable
* Adds note that collection names cannot be changed after publication
* Explains how to add custom thumbnails for wearables/items, and explains that these thumbnails must be 256x256px with transparent backgrounds

2021-06-24 20:32 UTC, nachomazzara requested changes
Thanks @schallock

2021-06-24 20:32 UTC, nachomazzara commented on _posts/wearables/2021-05-31-publishing-wearables.md
> +**The fee is a flat rate of 500 MANA per item (not NFT!) in your collection.**
I would link to the DAO proposal

2021-06-24 20:32 UTC, nachomazzara commented on _posts/wearables/2021-05-31-publishing-wearables.md
> +> **Note:** Currently, due to the time and resources required to review each collection submitted, **the 500 MANA publication fee is non-refundable**. If your collection is rejected and cannot be pub
It is already `published`. I would remove `and cannot be published`. 

Also, I would add that they have the chance to fix it.

2021-06-24 20:32 UTC, nachomazzara commented on _posts/wearables/2021-05-31-wearables-editor-user-guide.md
> +> The name of your collection cannot be changed after publication!
What do you think of moving this to the collection creation section?

2021-06-24 20:32 UTC, nachomazzara commented on _posts/wearables/2021-05-31-wearables-editor-user-guide.md
> +_Currently, due to the time and resources required to review each collection submitted, the 500 MANA publication fee is non-refundable. If your collection is rejected and cannot be published, you wil
same as above related to `cannot be published`

2021-06-25 13:49 UTC, ShibuyaMartin commented on _posts/wearables/2021-05-31-wearables-editor-user-guide.md
> +_Currently, due to the time and resources required to review each collection submitted, the 500 MANA publication fee is non-refundable. If your collection is rejected and cannot be published, you wil
"due to the time and resources required to review each collection submitted, the 500 MANA publication fee is non-refundable" --> is this the only reason for the 500 MANA to not be returned?

2021-06-25 13:50 UTC, ShibuyaMartin commented on _posts/wearables/2021-05-31-wearables-editor-user-guide.md
> +> The name of your collection cannot be changed after publication!
I would put this in the card just before publish as well @nachomazzara . Also saying the same about the rarities.

![image (8)](https://user-images.githubusercontent.com/25348765/123434729-2ad63900-d5a3-11eb-8ec9-61f6348a7412.png)

2021-06-25 13:51 UTC, ShibuyaMartin commented on _posts/wearables/2021-05-31-wearables-editor-user-guide.md
> +> The name of your collection cannot be changed after publication!
and maybe about the 500 MANA not be returned

2021-06-25 18:25 UTC, schallock commented on _posts/wearables/2021-05-31-wearables-editor-user-guide.md
> +_Currently, due to the time and resources required to review each collection submitted, the 500 MANA publication fee is non-refundable. If your collection is rejected and cannot be published, you wil
That's my understanding, yes. It's not that it's technically impossible to return, but the potential to receive the fee back would defeat the purpose of the fee in the first place.

2021-06-25 18:25 UTC, schallock commented on _posts/wearables/2021-05-31-wearables-editor-user-guide.md
> +> The name of your collection cannot be changed after publication!
Gotcha. Yes those two points we can add to the confirmation window. I'll work with @nachomazzara on this.

2021-06-25 18:35 UTC, merged