Update 2021-05-31-wearables-editor-user-guide.md
decentraland/old-documentation pull request #525
Opened 2022-01-11 15:57 UTC by ShibuyaMartin

@2fd @nearnshaw can you take a look at these changes, please? 

Added some images of the process and some more lines to be more clear about uploading wearables.

Thanks

2022-01-11 16:10 UTC, 2fd requested changes

2022-01-11 16:10 UTC, 2fd commented on _posts/wearables/2021-05-31-wearables-editor-user-guide.md
> +<img width="1135" alt="Screen Shot 2022-01-11 at 11 41 13" src="https://user-images.githubusercontent.com/25348765/148963649-e9e254cf-4415-4b0e-a939-d78407efb9f8.png">
- We should use our own domain to serve these images
- Give files a better name (like: werables-editor-01.png)
- Save these images on `/images/media/werables-editor`
- Use a better `alt` (like `Create a new Collection`)
- Use the {{ site.baseUrl }} placeholder

```html
<img src="{{ site.baseurl }}/images/media/werables-editor/werables-editor-01.png" alt="Create a new Collection" width="1135"/>
```

2022-02-18 20:05 UTC, nearnshaw approved these changes

2022-02-18 20:05 UTC, nearnshaw approved these changes

2022-02-18 20:06 UTC, nearnshaw approved these changes

2022-02-18 20:07 UTC, nearnshaw commented on _posts/wearables/2021-05-31-wearables-editor-user-guide.md
> +<img width="1135" alt="Screen Shot 2022-01-11 at 11 41 13" src="https://user-images.githubusercontent.com/25348765/148963649-e9e254cf-4415-4b0e-a939-d78407efb9f8.png">
I moved all the images to the folder and changed the links
@2fd  please approve, looks like it still can't be merged

2022-03-07 14:46 UTC, nearnshaw commented
@2fd 
can you please add an approval to this PR?
looks like it doesn't let me merge without that, since you requested changes

2022-03-07 14:47 UTC, 2fd approved these changes

2022-03-07 14:48 UTC, merged