Coding tips
decentraland/old-documentation pull request #60
Opened 2018-07-23 18:15 UTC by nearnshaw

A new page with a set of tips of things that aren't about the SDK but about TypeScript and how to use it in scenes

@eordano , @menduz ,  please review and merge

2018-07-24 22:22 UTC, menduz requested changes
The rest of the document looks good!

2018-07-24 22:22 UTC, menduz commented on _posts/sdk-reference/2018-01-01-SDK-Overview.md
> +- **Local scenes**: singleplayer scenes built using the SDK that allow a single player to interact with content in the scene. The script is run on a WebWorker.
It is still talking about singleplayer, probably change the description to tell something like
> **Local scenes**: intended to run inside the user's client. Your scene run inside a WebWorker, that means you don't need any server to create an experience
> **Remote scenes**: in some cases, you may want to create more complex experiences that require a centralized coordination or are too sensible to execute in every user's computers. These scenes run in a Node.js server and connect with the clients through a WebSockets interface.

2018-07-24 22:48 UTC, nearnshaw commented on _posts/sdk-reference/2018-01-01-SDK-Overview.md
> +- **Local scenes**: singleplayer scenes built using the SDK that allow a single player to interact with content in the scene. The script is run on a WebWorker.
This Pull Request was really only meant to create a new page with coding tips
(it ended up having a bunch of minor adjustments in other pages due to merge conflicts, but that's a different story)
For more clarity, I would make that change in the PR for the new version of the API,  otherwise this is going to be hell for the translators to go through

2018-07-24 23:33 UTC, nearnshaw commented on _posts/sdk-reference/2018-01-01-SDK-Overview.md
> +- **Local scenes**: singleplayer scenes built using the SDK that allow a single player to interact with content in the scene. The script is run on a WebWorker.
@menduz,  I added this in another branch, please accept to pr

2018-07-25 00:02 UTC, menduz approved these changes

2018-07-25 00:02 UTC, menduz commented
:shipit:

2018-07-25 00:11 UTC, merged