feat: Improved Linked Wearables documentation
decentraland/old-documentation pull request #638
Opened 2022-05-23 17:22 UTC by LautaroPetaccio

This PR improves the Linked Wearables documentation by adding information on:
- How to create a collection with the contract address as the ID.
- How to edit a collection name.
- How to edit a collection URN.
- How to delete a collection.
- How to upload items in bulk.
- How to upload a single item.
- How to edit an item's URN.
- How to edit items in bulk.
- How to build the APIs by querying a contract.

2022-05-23 17:56 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Even though there is a storage cost to upload the 3D representations of your Linked Wearables and also there is a cost for the Curation of your 3D models, the DAO will cover these fees in order to en
```suggestion
Even though there is a storage cost to upload the 3D representations of your Linked Wearables, and a cost for the Curation of your 3D models, the DAO will cover these fees in order to encourage new communities to bring their NFTs to Decentraland!
```

2022-05-23 18:02 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
> +After the DAO has approved the proposal, a set of Third Party managers will be set to operate with the all of the Linked Wearables features.
```suggestion
After the DAO has approved the proposal, a set of Third Party managers will be assigned to operate with the all of the Linked Wearables features.
```

2022-05-23 18:05 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
> +We strongly recommend that you choose a name that is unique and descriptive for the collection and **as the ID, the address of the NFT contract** that will be mapped to the Linked Wearables. Using th
for the collection and **as the ID, the address of the NFT contract** that will be mapped to the Linked Wearables

I think there is something wrong with the emphasis, maybe some extra text that was not removed

2022-05-23 18:06 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Linked wearable collections can be edited by Third Party Managers of the Third Party record they belong to. The collection can be renamed at any time but, **the ID (or URN) can be changed and the col
```suggestion
Linked wearable collections can be edited by Third Party Managers of the Third Party record they belong to. The collection can be renamed at any time but, **the ID (or URN) can be changed and the collection can be deleted only if they have no published wearables**.
```

2022-05-23 19:22 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
> +To delete Linked Wearable Collection follow these steps:
On both delete and update collection id or urn I would repeat the message about that it can be done only if there are no published wearables.

Useful because when reading the docs the person might look for these titles and ignore the message above.

2022-05-24 16:20 UTC, nachomazzara requested changes
Excellent work @LautaroPetaccio

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +After the DAO has approved the proposal, a set of Third Party managers will be set to operate with the all of the Linked Wearables features.
```suggestion
After the DAO has approved the proposal, a group of Third Party managers will be set to operate with all of the Linked Wearables features.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +We strongly recommend that you choose a name that is unique and descriptive for the collection and **as the ID, the address of the NFT contract** that will be mapped to the Linked Wearables. Using th
```suggestion
We strongly recommend that you choose a name that is unique and descriptive for the collection and **as the ID, the address of the NFT contract** that will be mapped to the Linked Wearables. Using the NFT address as the ID of your collection will prove to be helpful when creating the API.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Linked wearables are grouped in collections that can be created, edited and deleted by Third Party Managers. Each collection can contain an arbitrary number of Linked Wearables.
```suggestion
Linked wearables are grouped in collections that can be created, edited, and deleted by Third Party Managers. Each collection can contain an arbitrary number of Linked Wearables.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Linked wearable collections can be edited by Third Party Managers of the Third Party record they belong to. The collection can be renamed at any time but, **the ID (or URN) can be changed and the col
```suggestion
Linked wearable collections can be edited by Third Party Managers of the Third Party record they belong to. The collection can be renamed at any time but, **the ID (or URN) can be changed and the collection can be deleted only if there are no published wearables**.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +- The 3D model files of the wearable (GLB, GLTFs, texture files, etc).
```suggestion
- The 3D model files of the wearable (GLB, GLTFs, texture files, etc). **Mandatory**
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +- A `wearable.json` file containing the information of the wearable.
```suggestion
- A `wearable.json` file containing the information of the wearable. **Mandatory**
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +- An optional `thumbnail.png` file containing the thumbnail of the wearable that will be seen in the Builder and the world. If it is not provided, one will be generated using the 3D model.
```suggestion
- A `thumbnail.png` file containing the thumbnail of the wearable that will be seen in the Builder and the world. If it is not provided, one will be generated using the 3D model. **Optional**
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +- A `wearable.json` file containing the information of the wearable.
Can add a link to the `wearable.json` below?

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +  - Update a wearable in Bulk (which will be seen in the `Making changes in bulk` section)
Link to the section if it is possible

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +- The `id` field must contain the whole ID of the wearable, that is, the third party record id, the collection id and the item id `urn:decentraland:matic:collections-thirdparty:third-party-id:collect
```suggestion
- The `id` field must contain the whole ID of the wearable, that is, the third party record id, the collection id and the item id `urn:decentraland:matic:collections-thirdparty:third-party-id:collection-id:item-id`. We recommend the id to be formed as `urn:decentraland:matic:collections-thirdparty:third-party-id:contract-address:token-id`, that is, if our wearable will be mapped to the token `1` in the NFT contract `0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d`, we recommend the URN to be `urn:decentraland:matic:collections-thirdparty:third-party-id:0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d:1`.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +  into consideration the body shapes that we currently have, either 'urn:decentraland:off-chain:base-avatars:BaseMale' or 'urn:decentraland:off-chain:base-avatars:BaseFemale'. Each representation wil
```suggestion
  into consideration the body shapes that we currently have, either `urn:decentraland:off-chain:base-avatars:BaseMale` or `urn:decentraland:off-chain:base-avatars:BaseFemale`. Each representation will describe which models will be used for each body shape.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +  "id": "urn:decentraland:matic:collections-thirdparty:third-party-id:collection-id:item-id",
```suggestion
  "id": "urn:decentraland:matic:collections-thirdparty:third-party-id:0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d:1",
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +To add a custom thumbnail to the wearable, you can add a `thumbnail.png` file to the ZIP file and the file will be processed when uploaded..
```suggestion
To add a custom thumbnail to the wearable, you can add a `thumbnail.png` file to the ZIP file.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Following the same idea previously seen in the `Uploading models in bulk` section, third party managers can make changes to the wearables in bulk.
Link to the section if it is possible

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +  "id": "urn:decentraland:matic:collections-thirdparty:third-party-id:collection-id:item-id",
```suggestion
  "id": "urn:decentraland:matic:collections-thirdparty:third-party-id:0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d:1",
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Linked Wearables can be seen in world to review how the model will work once published.
```suggestion
Linked Wearables can be seen in world to review how the model will work once published and approved.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Once your wearables are ready, they must be published for curation. Publishing wearables **will consume slots**, a slot per wearable will be consumed upon publishing.
```suggestion
Once your wearables are ready, they must be published for curation. A slot per wearables will be consumed upon publishing.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
>  Note that it does not matter in which network your NFT project is: Ethereum, Polygon, Binance, etc. The API is needed to map the owner of the NFT to the 3D model (wearable) submitted to Decentraland.
This part was in the API section

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Having all the tokens that the an address owns, the API can easily build the response by building each of the assets:
```suggestion
Having all the tokens that an address owns, the API can easily build the response by mapping each of the assets:
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +- Created a collection which its ID or URN is the contract address of the NFTs that will represent or map to the Linked Wearables.
```suggestion
- Created a collection whose ID or URN is the contract address of the NFTs that will represent or map to the Linked Wearables.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +- Created wearables which IDs or URNs are the token ids of the NFTs that will represent or map to the Linked Wearables.
```suggestion
- Created wearables whose IDs or URNs are the token ids of the NFTs that will represent or map to the Linked Wearables.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +  "total": 100,
```suggestion
  "total": 2,
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +   2. Create or upload your wearables either by uploading them one by one or in bulk.
I would re-add this somewhere

```
Note that the URN uses `matic` for the protocol. This means that the third party registry smart contract has been deployed in the Matic network **BUT** it is not related to or limiting where your project can be created. Every urn for linked wearables items will use `matic` as the protocol. Remember that linked wearables work for any NFT project created at any network. So, if your project has been created in Ethereum, the urn of the item will have `matic` in the protocol and it is ok.
```

2022-05-24 16:20 UTC, nachomazzara commented on _posts/wearables/2022-04-05-linked-wearables.md
> +```
I would clarify that this is JUST an example of the API that will work ONLY if you have an NFT project and you will have one 3d model for each token minted. Also, that each project may use its own logic. The important thing is to map token ownership with the wearables submitted to DCL.

2022-05-25 11:59 UTC, LautaroPetaccio commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Linked wearables are grouped in collections that can be created, edited and deleted by Third Party Managers. Each collection can contain an arbitrary number of Linked Wearables.
In this case, the comma is not required as it's an enumeration of things that can be done to the collections.

2022-05-25 16:47 UTC, LautaroPetaccio commented on _posts/wearables/2022-04-05-linked-wearables.md
>  Note that it does not matter in which network your NFT project is: Ethereum, Polygon, Binance, etc. The API is needed to map the owner of the NFT to the 3D model (wearable) submitted to Decentraland.
I've moved it and re-written it.

2022-05-25 16:47 UTC, LautaroPetaccio commented on _posts/wearables/2022-04-05-linked-wearables.md
> +- A `wearable.json` file containing the information of the wearable.
I've added "required" at the start of each of the bullet points, making emphasis on its requirability, so it's clear which of the is mandatory or not.

2022-05-25 16:47 UTC, LautaroPetaccio commented on _posts/wearables/2022-04-05-linked-wearables.md
> +- The 3D model files of the wearable (GLB, GLTFs, texture files, etc).
I've added "required" at the start of each of the bullet points, making emphasis on its requirability, so it's clear which of the is mandatory or not.

2022-05-25 19:16 UTC, nachomazzara approved these changes

2022-05-26 13:09 UTC, LautaroPetaccio commented on _posts/wearables/2022-04-05-linked-wearables.md
> +```
I've added the `Important notice` down below with that information.

2022-05-26 16:34 UTC, LautaroPetaccio commented on _posts/wearables/2022-04-05-linked-wearables.md
> +We strongly recommend that you choose a name that is unique and descriptive for the collection and **as the ID, the address of the NFT contract** that will be mapped to the Linked Wearables. Using th
I've changed a bit the emphasis.

2022-05-26 19:32 UTC, nachomazzara approved these changes

2022-05-26 20:32 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
> +1. Select the items to be published and wait for the Curators Committee to approve them
I the quetion "Why should I select the items to be published intead of publishing them all?" worth answering here?

2022-05-26 20:38 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Note that the URNs in the examples use `matic` for the protocol. This means that the third party registry smart contract has been deployed in the Matic network **BUT** it is not related to or limitin
"the urn of the item will have `matic` in the protocol and it is ok."

Would it be nice to explain that it says matic because the information of the third party is stored in the matic network?

2022-05-26 20:40 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Note that the URNs in the examples use `matic` for the protocol. This means that the third party registry smart contract has been deployed in the Matic network **BUT** it is not related to or limitin
@nachomazzara already mentioned this on another comment 👍

2022-05-26 20:44 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
>  ## Summary
Would be nice that each bullet of the summery has an anchor to the respective documentation in this document. At least the main ones.

For example: 'Create a DAO proposal in the category “Linked Wearables Registry”. You’ll need to:' could have a link to 'http://0.0.0.0:4000/decentraland/linked-wearables/#dao-proposal' (with the proper domain)

2022-05-27 12:27 UTC, LautaroPetaccio commented on _posts/wearables/2022-04-05-linked-wearables.md
> +   2. Create or upload your wearables either by uploading them one by one or in bulk.
Added this information to the `important notice` in the `Building the API` section.

2022-05-27 12:28 UTC, LautaroPetaccio commented on _posts/wearables/2022-04-05-linked-wearables.md
> +1. Select the items to be published and wait for the Curators Committee to approve them
That's a great question. I think that if we wanted, we could explain a lot of the decisions taken, but I think that it will extend a lot the documentation.

2022-05-27 12:34 UTC, LautaroPetaccio commented on _posts/wearables/2022-04-05-linked-wearables.md
> +Note that the URNs in the examples use `matic` for the protocol. This means that the third party registry smart contract has been deployed in the Matic network **BUT** it is not related to or limitin
This was added in the important notice section!

2022-05-27 12:34 UTC, LautaroPetaccio commented on _posts/wearables/2022-04-05-linked-wearables.md
>  ## Summary
Changed the summary to have links in the bullet points that had one!

2022-05-27 14:24 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
> +1. Select the items to be published and wait for the Curators Committee to approve them
Fair enough. Let's keep it simple

2022-05-27 14:34 UTC, fzavalia commented on _posts/wearables/2022-04-05-linked-wearables.md
>  ## Summary
👏

2022-05-27 14:34 UTC, fzavalia approved these changes

2022-05-27 14:35 UTC, merged