Restructure docs
decentraland/old-documentation pull request #91
Opened 2018-08-31 15:39 UTC by nearnshaw

- Rename SDK Reference section -> Scene Coding Guide
- Rename Market -> Blockchain Interactions
- Moved doc "Blockchain operations" from SDK Ref -> Blockchain Interactions
- Renamed doc "Scene content guide" -> "Scene content"
- Got rid of "Introduction" doc in SDK Ref
- Rewrote doc "Coding Scenes", combining all the content that used to be in the Introduction docs of SDK Ref section and of Building Scenes section, and making it a bit easier to read
- Changed all links to point to new locations
- Added redirects on all pages that moved from their old locations

These are all things we agreed upon with Esteban as part of the restructure we need. There will be more changes later, once we have the new design of the docs site. Today we can't add new sections because there would be no link to go into them in the main page, so changes that rely on that will have to wait until the redesign.

@eordano  @matiasbargas  @menduz   please review and merge

@oscnet please use in Chinese translation

2018-08-31 15:46 UTC, menduz commented
We need a `SDK Reference` section. The coding guide might be another one. I, as a developer, will enter directly to `SDK Reference` a `coding guide` is something that I wouldn't visit

2018-09-03 12:57 UTC, cazala commented
IMO puting the Marketplace and the SDK ethereum controller under the same section (Blockchain interactions) is confusing... I'd rather have a "DApps" section (we could bundle Agora, Marketplace, how to use MetaMask, our rest apis) and have the SDK Ethereum and Identity controllers with the rest of the SDK.

2018-09-03 13:28 UTC, eordano requested changes
Scene Coding Guide -> Development Guide

2018-09-04 01:39 UTC, eordano approved these changes

2018-09-04 12:10 UTC, merged