Fix bugs in code
decentraland/old-documentation pull request #97
Opened 2018-09-14 17:53 UTC by nearnshaw

Please review and merge

@oscnet please take into account for translations

2018-09-14 21:32 UTC, eordano requested changes

2018-09-14 21:32 UTC, eordano commented on _posts/getting-started/2018-01-01-installation-guide.md
> +2.  Look for the version of \_decentraland-api being used and manually change it to the latest version of the SDK.
?

2018-09-19 18:44 UTC, nearnshaw commented on _posts/getting-started/2018-01-01-installation-guide.md
> +2.  Look for the version of \_decentraland-api being used and manually change it to the latest version of the SDK.
@eordano 
I made a fix for this

2018-09-20 14:15 UTC, eordano approved these changes

2018-09-20 14:16 UTC, merged